language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2
env:
  - MIX_ENV=test
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo service postgresql restart 12
before_script:
  - psql --version
  - cp config/test.travis.exs config/test.exs
script:
  - mix test
