language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2
addons:
  - postgres: "12"
env:
  - MIX_ENV=test
before_script:
  - psql --version
  - psql -c "CREATE ROLE postgres WITH CREATEDB PASSWORD 'postgres'" -p 5433
  - cp config/test.travis.exs config/test.exs
script:
  - mix test
