language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2
addons:
  - postgres: 12
env:
  - MIX_ENV=test
before_script:
  - psql --version
  - psql -c "CREATE ROLE postgres WITH CREATEDB PASSWORD 'postgres'"
script:
  - mix test
