language: elixir
elixir:
  - 1.10
otp_release:
  - 22.2
addons:
  - postgresql: "12"
env:
  - MIX_ENV=test
before_script:
  - psql --version
  - psql -c "CREATE ROLE travis SUPERUSER LOGIN CREATEDB;" -U postgres
  - cp config/test.travis.exs config/test.exs
script:
  - mix test
