name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 30s
          --health-timeout 15s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1-otp-22 # Define the elixir version [required]
        otp-version: 22.2.6 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
